### 피쳐 플래그 생성
POST /feature-flag-config HTTP/1.1
Host: localhost:8080
Content-Type: application/json
Content-Length: 178

{
  "feature": "MAIL_SERVICE",
  "options": ["sendgrid","sendgrid","sendgrid","sendgrid","sendgrid","mailgun","mailgun","mailgun","directSend","directSend"],
  "isActive": true
}

### 피쳐 플래그 수정
PUT /feature-flag-config/1 HTTP/1.1
Host: localhost:8080
Content-Type: application/json
Content-Length: 124

{
  "feature": "MAIL_SERVICE",
  "options": ["sendgrid","mailgun", "mailgun", "mailgun", "directSend"],
  "isActive": true
}


### 피쳐 플래그 조회
GET /feature-flag-config HTTP/1.1
Host: localhost:8080

### 피쳐 플래그 삭제
DELETE /feature-flag-config/1 HTTP/1.1
Host: localhost:8080


### 메일 전송
POST /mail HTTP/1.1
Host: localhost:8080
Content-Type: application/json
Content-Length: 107

{
  "from": "jun@doodlin.co.kr",
  "to": "to-jun@doodlin.co.kr",
  "userId": 3,
  "content": "ZZ"
}


### 메일 전송 벌크 테스트 (1000건)
POST /mail/bulk HTTP/1.1
Host: localhost:8080
Content-Type: application/json
Content-Length: 107

{
  "from": "jun@doodlin.co.kr",
  "to": "to-jun@doodlin.co.kr",
  "userId": 3,
  "content": "ZZ"
}


### 메일 통계 조회
GET /mail HTTP/1.1
Host: localhost:8080